version: 2.1

jobs:
  build:
    docker:
      - image: cimg/python:3.11  # Official CircleCI Python image

    working_directory: ~/repo

    steps:
      - checkout  # Automatically clones your GitLab repo with webhook integration

      - run:
          name: Install dependencies
          command: |
            python -m venv venv
            . venv/bin/activate
            pip install --upgrade pip
            pip install sqlalchemy pytest flake8 coverage

      - run:
          name: Lint the code
          command: |
            . venv/bin/activate
            flake8 *.py || echo "Lint warnings found."

      - run:
          name: Run tests and generate coverage report
          command: |
            . venv/bin/activate
            coverage run --omit=*/site-packages/*,*/dist-packages/* test_point_manager.py
            coverage report

      - run:
          name: Package the project
          command: |
            mkdir -p dist
            zip -r dist/point_project.zip *.py

      - store_artifacts:
          path: dist/point_project.zip
          destination: point_project.zip
