name: GitLab → GitHub CI for Point Project

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  point-pipeline:
    name: Clone GitLab & Run Python Pipeline
    runs-on: ubuntu-latest

    steps:
    # Step 1: Install Git
    - name: Install Git
      run: sudo apt-get update && sudo apt-get install -y git

    # Step 2: Clone the GitLab repo using PAT
    - name: Clone GitLab repo
      run: |
        git clone https://${{ secrets.GITLAB_USERNAME }}:${{ secrets.GITLAB_TOKEN }}@gitlab-acit4850-w2025-group19.canadacentral.cloudapp.azure.com/group2/point.git repo
        ls repo

    # Step 3: Set up Python
    - name: Set up Python 3.11
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    # Step 4: Install dependencies
    - name: Install dependencies
      run: |
        cd repo
        python -m pip install --upgrade pip
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # Step 5: Lint
    - name: Lint Python files
      run: |
        cd repo
        pip install pylint
        pylint *.py || true

    # Step 6: Test
    - name: Run Unit Tests
      run: |
        cd repo
        pip install pytest
        pytest || echo "Tests failed or not found."

    # Step 7: Zip source code
    - name: Zip Python files
      run: |
        cd repo
        mkdir -p dist
        zip -r dist/point-pipeline-${{ github.run_number }}.zip . -x "*.git*" "venv/*"

    # Step 8: Upload Artifact
    - name: Upload zipped code
      uses: actions/upload-artifact@v4
      with:
        name: point-pipeline-zip
        path: repo/dist/point-pipeline-${{ github.run_number }}.zip
