name: Python CI Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Clone GitLab Repository
        run: |
          git clone https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab-acit4850-w2025-group19.canadacentral.cloudapp.azure.com/group2/point.git gitlab-repo

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd gitlab-repo
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install flake8 pytest

      - name: Lint with flake8
        run: |
          cd gitlab-repo
          flake8 . --exit-zero

      - name: Run tests with pytest
        run: |
          cd gitlab-repo
          pytest || true

      - name: Package the project
        run: |
          cd gitlab-repo
          zip -r project.zip .

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: python-project
          path: gitlab-repo/project.zip
