name: Python CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout GitHub repository
      uses: actions/checkout@v3

    - name: Clone GitLab Repository
      run: |
        git clone https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.com/andrewkim0430/dev-team-ci-cd.git gitlab-repo
        cd gitlab-repo

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.11'

    - name: Install dependencies
      run: |
        cd gitlab-repo
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    - name: Run lint checks
      run: |
        cd gitlab-repo
        pylint **/*.py || true

    - name: Run tests
      run: |
        cd gitlab-repo
        pytest

    - name: Package the project
      run: |
        cd gitlab-repo
        zip -r project.zip .
