name: CI Pipeline - Point Project

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  point-pipeline:
    name: Point Python Pipeline
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the mirrored GitLab repo code
      - name: Checkout code
        uses: actions/checkout@v4

      # Step 2: Setup Python 3.11
      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      # Step 3: Install dependencies
      - name: Install requirements
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      # Step 4: Lint with pylint
      - name: Run Lint
        run: |
          pip install pylint
          pylint *.py || true

      # Step 5: Run Unit Tests
      - name: Run Tests
        run: |
          pip install pytest
          pytest || echo "Some tests failed or no tests found."

      # Step 6: Zip Python Files
      - name: Zip Python Files
        run: |
          mkdir -p dist
          zip -r dist/point-pipeline-${{ github.run_number }}.zip . -x "*.git*" "venv/*" "__pycache__/*"

      # Step 7: Upload Artifact
      - name: Upload ZIP Artifact
        uses: actions/upload-artifact@v4
        with:
          name: point-pipeline-artifact
          path: dist/point-pipeline-${{ github.run_number }}.zip
